<script lang="ts">
	import { onMount } from 'svelte';
	import { apiData } from '$lib/api';
	import AssetManagementShell from '$lib/components/AssetManagementShell.svelte';
	type Branch={id:number;code:string;name:string};
	type Room={id:number;code:string;name:string;floor:string|null;branchId:number;branch:Branch};
	type Location={id:number;code:string;name:string;kind:string|null;roomId:number;room:Room};
	type Tab='branches'|'rooms'|'locations';
	let role=$state(''); let tab=$state<Tab>('branches'); let branches=$state<Branch[]>([]); let rooms=$state<Room[]>([]); let locations=$state<Location[]>([]); let message=$state(''); let editingId=$state<number|null>(null);
	let form=$state({code:'',name:'',branchId:'',floor:'',roomId:'',kind:''});
	const title=$derived(tab==='branches'?'Branches':tab==='rooms'?'Rooms':'Storage locations');
	function reset(){editingId=null;form={code:'',name:'',branchId:branches[0]?String(branches[0].id):'',floor:'',roomId:rooms[0]?String(rooms[0].id):'',kind:''};message='';}
	async function load(){const session=await fetch('/v1/auth/session');if(!session.ok){message='Please sign in to continue.';return;}role=(await apiData<{user:{role:string}}>(session)).user.role;const responses=await Promise.all([fetch('/v1/branches?limit=500'),fetch('/v1/rooms?limit=500'),fetch('/v1/storage-locations?limit=500')]);if(responses.some((response)=>!response.ok)){message='Unable to load location data.';return;}[branches,rooms,locations]=await Promise.all([apiData<Branch[]>(responses[0]),apiData<Room[]>(responses[1]),apiData<Location[]>(responses[2])]);if(!editingId)reset();}
	function edit(item:Branch|Room|Location){editingId=item.id;form={code:item.code,name:item.name,branchId:'branchId' in item?String(item.branchId):'',floor:'floor' in item?item.floor??'':'',roomId:'roomId' in item?String(item.roomId):'',kind:'kind' in item?item.kind??'':''};}
	async function save(){const endpoint=tab==='locations'?'storage-locations':tab;const body=tab==='branches'?{code:form.code,name:form.name}:tab==='rooms'?{code:form.code,name:form.name,branchId:form.branchId,floor:form.floor}:{code:form.code,name:form.name,roomId:form.roomId,kind:form.kind};const response=await fetch(`/v1/${endpoint}${editingId?'/'+editingId:''}`,{method:editingId?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!response.ok){message='Unable to save this item. Check required fields and duplicate values.';return;}await load();reset();}
	async function remove(item:Branch|Room|Location){if(!confirm(`Delete ${item.name}?`))return;const endpoint=tab==='locations'?'storage-locations':tab;const response=await fetch(`/v1/${endpoint}/${item.id}`,{method:'DELETE'});if(!response.ok){message='This item is in use or could not be deleted.';return;}await load();reset();}
	function select(next:Tab){tab=next;reset();}
	onMount(()=>{void load()});
</script>
<AssetManagementShell title="Locations" active="">
	<div class="heading"><div><p>LOCATION HIERARCHY</p><h1>Locations</h1><span>Maintain branches, rooms and the exact storage positions used by assets.</span></div></div>
	<div class="tabs" role="tablist"><button class:active={tab==='branches'} onclick={()=>select('branches')}>Branches <b>{branches.length}</b></button><button class:active={tab==='rooms'} onclick={()=>select('rooms')}>Rooms <b>{rooms.length}</b></button><button class:active={tab==='locations'} onclick={()=>select('locations')}>Storage locations <b>{locations.length}</b></button></div>
	{#if message}<p class="notice">{message}</p>{/if}
	<section class="panel"><div class="panel-title"><div><small>MASTER DATA</small><h2>{title}</h2></div><span>Branch → Room → Storage location</span></div>
		{#if (role==='system_administrator'||role==='business_administrator')}<form onsubmit={(event)=>{event.preventDefault();void save();}}><label>Code<input bind:value={form.code} required maxlength="64" /></label><label>Name<input bind:value={form.name} required maxlength="128" /></label>{#if tab==='rooms'}<label>Branch<select bind:value={form.branchId} required>{#each branches as branch}<option value={branch.id}>{branch.name}</option>{/each}</select></label><label>Floor<input bind:value={form.floor} maxlength="64" placeholder="e.g. 3F" /></label>{:else if tab==='locations'}<label>Room<select bind:value={form.roomId} required>{#each rooms as room}<option value={room.id}>{room.branch.name} / {room.name}</option>{/each}</select></label><label>Kind<input bind:value={form.kind} maxlength="64" placeholder="e.g. ROOM" /></label>{/if}<div class="actions"><button class="primary" type="submit">{editingId?'Save changes':'Add '+title.slice(0,-1).toLowerCase()}</button>{#if editingId}<button class="secondary" type="button" onclick={reset}>Cancel</button>{/if}</div></form>{/if}
		<div class="table-wrap"><table><thead><tr><th>Code</th><th>Name</th>{#if tab==='rooms'}<th>Branch</th><th>Floor</th>{:else if tab==='locations'}<th>Branch / room</th><th>Kind</th>{/if}{#if (role==='system_administrator'||role==='business_administrator')}<th></th>{/if}</tr></thead><tbody>{#if tab==='branches'}{#each branches as item}<tr><td><strong>{item.code}</strong></td><td>{item.name}</td>{#if (role==='system_administrator'||role==='business_administrator')}<td class="row-actions"><button onclick={()=>edit(item)}>Edit</button><button class="danger" onclick={()=>void remove(item)}>Delete</button></td>{/if}</tr>{/each}{:else if tab==='rooms'}{#each rooms as item}<tr><td><strong>{item.code}</strong></td><td>{item.name}</td><td>{item.branch.name}</td><td>{item.floor??'—'}</td>{#if (role==='system_administrator'||role==='business_administrator')}<td class="row-actions"><button onclick={()=>edit(item)}>Edit</button><button class="danger" onclick={()=>void remove(item)}>Delete</button></td>{/if}</tr>{/each}{:else}{#each locations as item}<tr><td><strong>{item.code}</strong></td><td>{item.name}</td><td>{item.room.branch.name}<small>{item.room.name}</small></td><td>{item.kind??'—'}</td>{#if (role==='system_administrator'||role==='business_administrator')}<td class="row-actions"><button onclick={()=>edit(item)}>Edit</button><button class="danger" onclick={()=>void remove(item)}>Delete</button></td>{/if}</tr>{/each}{/if}</tbody></table></div>
	</section>
</AssetManagementShell>
<style>.heading{margin-bottom:20px}.heading p,.panel-title small{margin:0;color:#1abb9c;font-size:11px;font-weight:700;letter-spacing:.08em}.heading h1{margin:4px 0;font-size:30px}.heading span,.panel-title>span{color:var(--muted);font-size:13px}.tabs{display:flex;gap:4px;margin-bottom:14px;border-bottom:1px solid var(--border)}.tabs button{padding:10px 14px;background:transparent!important;border-bottom:2px solid transparent;color:var(--muted)!important}.tabs button.active{border-color:#1abb9c;color:var(--text)!important}.tabs b{margin-left:5px;padding:2px 6px;border-radius:10px;background:var(--surface-secondary);font-size:10px}.notice{color:#d09b27}.panel{padding:20px;background:var(--surface);border:1px solid var(--border);border-radius:6px}.panel-title{display:flex;justify-content:space-between;align-items:end;margin-bottom:18px}.panel-title h2{margin:4px 0 0;font-size:18px}form{display:grid;grid-template-columns:repeat(4,minmax(120px,1fr));gap:10px;margin-bottom:20px;padding:14px;background:var(--surface-secondary);border:1px solid var(--border);border-radius:5px}label{display:grid;gap:5px;font-size:12px}input,select{padding:8px;border:1px solid var(--border);border-radius:4px;background:var(--surface);color:var(--text)}.actions{display:flex;align-items:end;gap:8px}.actions button{height:35px;padding:0 12px;border-radius:4px}.primary{background:#066fd1!important;color:#fff!important}.secondary{background:#6c757d!important;color:#fff!important}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:11px;border-bottom:1px solid var(--border);text-align:left}td small{display:block;color:var(--muted)}.row-actions{text-align:right;white-space:nowrap}.row-actions button{background:transparent!important;color:#066fd1!important}.row-actions .danger{color:#d63939!important}@media(max-width:800px){form{grid-template-columns:1fr 1fr}.panel-title{display:grid;gap:4px}}@media(max-width:520px){form{grid-template-columns:1fr}.tabs{overflow:auto}}</style>
