<script lang="ts">
	import { afterNavigate } from '$app/navigation';
	import { apiData } from '$lib/api';
	import AssetManagementShell from '$lib/components/AssetManagementShell.svelte';
	import CpuTypesPage from '$lib/components/CpuTypesPage.svelte';
	import MasterList from '$lib/components/MasterList.svelte';
	import DatePicker from '$lib/components/DatePicker.svelte';
	import SearchSelect from '$lib/components/SearchSelect.svelte';
	import '$lib/styles/add-button.css';
	import { tick } from 'svelte';
	type Resource='it-asset-types'|'manufacturers'|'cpu-types'|'operating-systems'|'it-asset-statuses';
	type Item={id:number;code:string;name?:string;managementCodePrefix?:string;displayName?:string;sortOrder:number;manufacturerId?:number;manufacturer?:{name:string};series?:string;modelNumber?:string;vendor?:string;product?:string;version?:string;edition?:string|null;architecture?:string|null;officialUrl?:string|null;sourceCheckedOn?:string|null;supportsCpu?:boolean;supportsRam?:boolean;supportsOs?:boolean;supportsLoginUsername?:boolean;disposalDatePolicy?:string};
	const labels:Record<Resource,string>={'it-asset-types':'IT asset types',manufacturers:'Manufacturers','cpu-types':'CPU types','operating-systems':'Operating systems','it-asset-statuses':'IT asset statuses'};
	let { data }: { data: { resource: string } } = $props();
	const allowed=new Set(Object.keys(labels)); const normalizeResource=(value:string):Resource=>allowed.has(value)?value as Resource:'it-asset-types'; const resource=$derived(normalizeResource(data.resource)); let role=$state(''); let items=$state<Item[]>([]); let manufacturers=$state<Item[]>([]); let editing=$state<Item|null>(null); let message=$state('');
	const blank=()=>({code:'',name:'',managementCodePrefix:'',displayName:'',sortOrder:'0',manufacturerId:'',series:'',modelNumber:'',vendor:'',product:'',version:'',edition:'',architecture:'',officialUrl:'',sourceCheckedOn:'',supportsCpu:false,supportsRam:false,supportsOs:false,supportsLoginUsername:false,disposalDatePolicy:'prohibited'}); let form=$state(blank()); const title=$derived(labels[resource]);
	let list=$state<MasterList>();
	let columns=$derived(resource==='it-asset-types'?[{key:'code',label:'Code',value:(item:Item)=>item.code},{key:'name',label:'Name',value:(item:Item)=>item.name},{key:'managementCodePrefix',label:'Prefix',value:(item:Item)=>item.managementCodePrefix},{key:'sortOrder',label:'Order',value:(item:Item)=>item.sortOrder}]:resource==='manufacturers'?[{key:'code',label:'Code',value:(item:Item)=>item.code},{key:'name',label:'Name',value:(item:Item)=>item.name},{key:'officialUrl',label:'Official URL',value:(item:Item)=>item.officialUrl??''},{key:'sortOrder',label:'Order',value:(item:Item)=>item.sortOrder}]:resource==='operating-systems'?[{key:'code',label:'Code',value:(item:Item)=>item.code},{key:'displayName',label:'Name',value:(item:Item)=>item.displayName},{key:'vendor',label:'Vendor',value:(item:Item)=>item.vendor},{key:'product',label:'Product',value:(item:Item)=>item.product},{key:'version',label:'Version',value:(item:Item)=>item.version},{key:'sortOrder',label:'Order',value:(item:Item)=>item.sortOrder}]:[{key:'code',label:'Code',value:(item:Item)=>item.code},{key:'name',label:'Name',value:(item:Item)=>item.name},{key:'disposalDatePolicy',label:'Disposal date',value:(item:Item)=>item.disposalDatePolicy},{key:'sortOrder',label:'Order',value:(item:Item)=>item.sortOrder}]);
	let canManage=$derived(role==='system_administrator'||role==='business_administrator');
	let formOpen=$state(false);
	let errors=$state<Record<string,string>>({});let formElement=$state<HTMLFormElement>();
	let sourceDateOpen=$state(false);
	function reset(){editing=null;formOpen=false;sourceDateOpen=false;errors={};form=blank();form.manufacturerId=manufacturers[0]?String(manufacturers[0].id):'';message='';}
	async function load(){const session=await fetch('/v1/auth/session');if(!session.ok){message='Please sign in to continue.';return;}role=(await apiData<{user:{role:string}}>(session)).user.role;const response=await fetch('/v1/manufacturers?limit=500');manufacturers=response.ok?await apiData<Item[]>(response):[];if(!editing)reset();}
	function edit(item:Item){editing=item;formOpen=true;errors={};form={code:item.code,name:item.name??'',managementCodePrefix:item.managementCodePrefix??'',displayName:item.displayName??'',sortOrder:String(item.sortOrder),manufacturerId:item.manufacturerId?String(item.manufacturerId):'',series:item.series??'',modelNumber:item.modelNumber??'',vendor:item.vendor??'',product:item.product??'',version:item.version??'',edition:item.edition??'',architecture:item.architecture??'',officialUrl:item.officialUrl??'',sourceCheckedOn:item.sourceCheckedOn?.slice(0,10)??'',supportsCpu:item.supportsCpu??false,supportsRam:item.supportsRam??false,supportsOs:item.supportsOs??false,supportsLoginUsername:item.supportsLoginUsername??false,disposalDatePolicy:item.disposalDatePolicy??'prohibited'};void tick().then(()=>formElement?.querySelector<HTMLInputElement>('[name="code"]')?.focus());}
	function add(){reset();formOpen=true;void tick().then(()=>formElement?.querySelector<HTMLInputElement>('[name="code"]')?.focus());}
	async function save(){const required=['code',...(resource==='operating-systems'?['vendor','product','version','displayName']:['name']),...(resource==='it-asset-types'?['managementCodePrefix']:[])];errors={};for(const key of required){if(!String(form[key as keyof typeof form]??'').trim())errors[key]=`${key.replace(/([A-Z])/g,' $1')} is required.`;}if(resource==='it-asset-types'&&form.managementCodePrefix&&!/^[A-Z]{3,5}$/.test(form.managementCodePrefix))errors.managementCodePrefix='Use 3 to 5 uppercase letters.';if(!/^\d+$/.test(form.sortOrder))errors.sortOrder='Enter a non-negative whole number.';if(form.officialUrl&&!/^https?:\/\//i.test(form.officialUrl))errors.officialUrl='Enter a valid URL.';if(Object.keys(errors).length){await tick();formElement?.querySelector<HTMLElement>('[aria-invalid="true"]')?.focus();return;}const response=await fetch(`/v1/${resource}${editing?'/'+editing.id:''}`,{method:editing?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});if(!response.ok){const payload=await response.json().catch(()=>null) as {error?:{details?:{field?:string}[]}}|null;const field=payload?.error?.details?.[0]?.field;if(field&&['code','name','displayName','managementCodePrefix'].includes(field)){errors[field]='This value already exists.';await tick();formElement?.querySelector<HTMLElement>('[aria-invalid="true"]')?.focus();}else message='Unable to save this item. Check required fields and duplicate values.';return;}await load();reset();await list?.refresh();}
	async function remove(item:Item){if(!confirm(`Delete ${item.name??item.displayName??item.code}?`))return;const response=await fetch(`/v1/${resource}/${item.id}`,{method:'DELETE'});if(!response.ok){message='This item is in use or could not be deleted.';return;}await load();reset();await list?.refresh();}
	afterNavigate(()=>{if(resource==='cpu-types')return;reset();void load();});
</script>
<svelte:window onkeydown={(event)=>{if(event.key==='Escape'&&sourceDateOpen){sourceDateOpen=false;void tick().then(()=>document.querySelector<HTMLButtonElement>('[data-field="master-source-checked"] .date-trigger')?.focus());}}} onclick={(event)=>{if(sourceDateOpen&&event.target instanceof Element&&!event.target.closest('[data-field="master-source-checked"]'))sourceDateOpen=false;}} />
{#if resource==='cpu-types'}
	<CpuTypesPage />
{:else}
<AssetManagementShell {title} active="">
	<div class="heading"><div><p>IT ASSET CONFIGURATION</p><h1>{title}</h1><span>Maintain the controlled values used by IT asset records.</span></div>{#if canManage}<button class="app-add-button" type="button" onclick={add}><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M8 2v12M2 8h12" /></svg>Add item</button>{/if}</div>
	{#if message}<p class="notice">{message}</p>{/if}
	<section class="panel">
		{#if canManage && formOpen}<form bind:this={formElement} novalidate onsubmit={(event)=>{event.preventDefault();void save();}}><label>Code <span class="required">*</span><input name="code" bind:value={form.code} maxlength="64" aria-invalid={!!errors.code} aria-describedby={errors.code?'master-code-error':undefined} oninput={()=>errors.code=''}/>{#if errors.code}<small id="master-code-error" class="field-error">{errors.code}</small>{/if}</label>
			{#if resource==='it-asset-types'||resource==='manufacturers'||resource==='it-asset-statuses'}<label>Name <span class="required">*</span><input bind:value={form.name} maxlength="128" aria-invalid={!!errors.name} aria-describedby={errors.name?'master-name-error':undefined} oninput={()=>errors.name=''}/>{#if errors.name}<small id="master-name-error" class="field-error">{errors.name}</small>{/if}</label>{/if}
			{#if resource==='it-asset-types'}<label>Management code prefix <span class="required">*</span><input bind:value={form.managementCodePrefix} minlength="3" maxlength="5" placeholder="e.g. NPC" aria-invalid={!!errors.managementCodePrefix} aria-describedby={errors.managementCodePrefix?'master-prefix-error':undefined} oninput={()=>errors.managementCodePrefix=''}/>{#if errors.managementCodePrefix}<small id="master-prefix-error" class="field-error">{errors.managementCodePrefix}</small>{/if}</label>{/if}
			{#if resource==='operating-systems'}<label>Vendor <span class="required">*</span><input bind:value={form.vendor} aria-invalid={!!errors.vendor} aria-describedby={errors.vendor?'master-vendor-error':undefined} oninput={()=>errors.vendor=''}/>{#if errors.vendor}<small id="master-vendor-error" class="field-error">{errors.vendor}</small>{/if}</label><label>Product <span class="required">*</span><input bind:value={form.product} aria-invalid={!!errors.product} aria-describedby={errors.product?'master-product-error':undefined} oninput={()=>errors.product=''}/>{#if errors.product}<small id="master-product-error" class="field-error">{errors.product}</small>{/if}</label><label>Version <span class="required">*</span><input bind:value={form.version} aria-invalid={!!errors.version} aria-describedby={errors.version?'master-version-error':undefined} oninput={()=>errors.version=''}/>{#if errors.version}<small id="master-version-error" class="field-error">{errors.version}</small>{/if}</label><label>Edition<input bind:value={form.edition} /></label><label>Architecture<input bind:value={form.architecture} /></label><label>Display name <span class="required">*</span><input bind:value={form.displayName} aria-invalid={!!errors.displayName} aria-describedby={errors.displayName?'master-display-error':undefined} oninput={()=>errors.displayName=''}/>{#if errors.displayName}<small id="master-display-error" class="field-error">{errors.displayName}</small>{/if}</label>{/if}
			{#if resource==='manufacturers'||resource==='operating-systems'}<label>Official URL<input bind:value={form.officialUrl} type="url" maxlength="1000" aria-invalid={!!errors.officialUrl} aria-describedby={errors.officialUrl?'master-url-error':undefined} oninput={()=>errors.officialUrl=''}/>{#if errors.officialUrl}<small id="master-url-error" class="field-error">{errors.officialUrl}</small>{/if}</label><DatePicker label="Source checked" field="master-source-checked" value={form.sourceCheckedOn} open={sourceDateOpen} onToggle={()=>sourceDateOpen=!sourceDateOpen} onSelect={(value)=>{form.sourceCheckedOn=value;sourceDateOpen=false;}} />{/if}
			{#if resource==='it-asset-statuses'}<SearchSelect label="Disposal date" field="disposalDatePolicy" value={form.disposalDatePolicy} options={[{value:'prohibited',label:'Prohibited'},{value:'optional',label:'Optional'},{value:'required',label:'Required'}]} onSelect={(value)=>form.disposalDatePolicy=value} />{/if}
			<label>Sort order <span class="required">*</span><input bind:value={form.sortOrder} type="number" min="0" aria-invalid={!!errors.sortOrder} aria-describedby={errors.sortOrder?'master-order-error':undefined} oninput={()=>errors.sortOrder=''}/>{#if errors.sortOrder}<small id="master-order-error" class="field-error">{errors.sortOrder}</small>{/if}</label>
			{#if resource==='it-asset-types'}<fieldset><legend>Supported fields</legend><label><input bind:checked={form.supportsCpu} type="checkbox" />CPU</label><label><input bind:checked={form.supportsRam} type="checkbox" />RAM</label><label><input bind:checked={form.supportsOs} type="checkbox" />OS</label><label><input bind:checked={form.supportsLoginUsername} type="checkbox" />Login username</label></fieldset>{/if}
			<div class="actions"><button class="primary" type="submit">Save</button><button class="secondary" type="button" onclick={reset}>Cancel</button></div></form>{/if}
		<MasterList bind:this={list} endpoint={`/v1/${resource}`} {columns} {title} {canManage} onEdit={(item)=>edit(item as Item)} onDelete={(item)=>remove(item as Item)} />
	</section>
</AssetManagementShell>
{/if}
<style>.heading{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:24px}.heading p{margin:0;color:#1abb9c;font-size:11px;font-weight:700;letter-spacing:.08em}.heading h1{margin:4px 0;font-size:30px}.heading span{color:var(--muted)}.notice{color:#d63939}.panel{width:100%;min-width:0;box-sizing:border-box}form{display:grid;grid-template-columns:repeat(4,minmax(130px,1fr));gap:10px;margin-bottom:20px;padding:14px;background:var(--surface-secondary);border:1px solid var(--border);border-radius:5px}label{display:grid;gap:5px;font-size:12px}input{height:36px;padding:0 12px;border:1px solid var(--border);border-radius:4px;background:var(--surface);color:var(--text)}fieldset{display:flex;align-items:center;gap:12px;margin:0;padding:7px 10px;border:1px solid var(--border);border-radius:4px}fieldset legend{font-size:11px}fieldset label{display:flex;align-items:center;gap:4px}.actions{display:flex;align-items:end;gap:8px}.actions button{height:35px;padding:0 12px;border:0;border-radius:4px;color:white}.primary{background:#066fd1}.secondary{background:#6c757d}@media(max-width:900px){form{grid-template-columns:1fr 1fr}}@media(max-width:700px){.heading{align-items:stretch;flex-direction:column}}@media(max-width:560px){form{grid-template-columns:1fr}}.required{color:#d63939}input[aria-invalid=true]{border-color:#d63939}.field-error{color:#d63939;font-size:11px}</style>
