<script lang="ts">
	import { afterNavigate } from '$app/navigation';
	import { apiData } from '$lib/api';
	import AssetManagementShell from '$lib/components/AssetManagementShell.svelte';
	type Resource='it-asset-types'|'manufacturers'|'cpu-types'|'operating-systems'|'it-asset-statuses';
	type Item={id:number;code:string;name?:string;managementCodePrefix?:string;displayName?:string;sortOrder:number;manufacturerId?:number;manufacturer?:{name:string};series?:string;modelNumber?:string;vendor?:string;product?:string;version?:string;edition?:string|null;architecture?:string|null;officialUrl?:string|null;sourceCheckedOn?:string|null;supportsCpu?:boolean;supportsRam?:boolean;supportsOs?:boolean;supportsLoginUsername?:boolean;disposalDatePolicy?:string};
	const labels:Record<Resource,string>={'it-asset-types':'IT asset types',manufacturers:'Manufacturers','cpu-types':'CPU types','operating-systems':'Operating systems','it-asset-statuses':'IT asset statuses'};
	let { data }: { data: { resource: string } } = $props();
	const allowed=new Set(Object.keys(labels)); const normalizeResource=(value:string):Resource=>allowed.has(value)?value as Resource:'it-asset-types'; const resource=$derived(normalizeResource(data.resource)); let role=$state(''); let items=$state<Item[]>([]); let manufacturers=$state<Item[]>([]); let editing=$state<Item|null>(null); let message=$state('');
	const blank=()=>({code:'',name:'',managementCodePrefix:'',displayName:'',sortOrder:'0',manufacturerId:'',series:'',modelNumber:'',vendor:'',product:'',version:'',edition:'',architecture:'',officialUrl:'',sourceCheckedOn:'',supportsCpu:false,supportsRam:false,supportsOs:false,supportsLoginUsername:false,disposalDatePolicy:'prohibited'}); let form=$state(blank()); const title=$derived(labels[resource]);
	function reset(){editing=null;form=blank();form.manufacturerId=manufacturers[0]?String(manufacturers[0].id):'';message='';}
	async function load(){const session=await fetch('/v1/auth/session');if(!session.ok){message='Please sign in to continue.';return;}role=(await apiData<{user:{role:string}}>(session)).user.role;const responses=await Promise.all([fetch(`/v1/${resource}?limit=500`),fetch('/v1/manufacturers?limit=500')]);if(!responses[0].ok){message='The requested master resource was not found.';items=[];return;}items=await apiData<Item[]>(responses[0]);manufacturers=responses[1].ok?await apiData<Item[]>(responses[1]):[];if(!editing)reset();}
	function edit(item:Item){editing=item;form={code:item.code,name:item.name??'',managementCodePrefix:item.managementCodePrefix??'',displayName:item.displayName??'',sortOrder:String(item.sortOrder),manufacturerId:item.manufacturerId?String(item.manufacturerId):'',series:item.series??'',modelNumber:item.modelNumber??'',vendor:item.vendor??'',product:item.product??'',version:item.version??'',edition:item.edition??'',architecture:item.architecture??'',officialUrl:item.officialUrl??'',sourceCheckedOn:item.sourceCheckedOn?.slice(0,10)??'',supportsCpu:item.supportsCpu??false,supportsRam:item.supportsRam??false,supportsOs:item.supportsOs??false,supportsLoginUsername:item.supportsLoginUsername??false,disposalDatePolicy:item.disposalDatePolicy??'prohibited'};}
	async function save(){const response=await fetch(`/v1/${resource}${editing?'/'+editing.id:''}`,{method:editing?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});if(!response.ok){message='Unable to save this item. Check required fields and duplicate values.';return;}await load();reset();}
	async function remove(item:Item){if(!confirm(`Delete ${item.name??item.displayName??item.code}?`))return;const response=await fetch(`/v1/${resource}/${item.id}`,{method:'DELETE'});if(!response.ok){message='This item is in use or could not be deleted.';return;}await load();reset();}
	afterNavigate(()=>{reset();void load();});
</script>
<AssetManagementShell {title} active="">
	<div class="heading"><div><p>IT ASSET CONFIGURATION</p><h1>{title}</h1><span>Maintain the controlled values used by IT asset records.</span></div></div>
	{#if message}<p class="notice">{message}</p>{/if}
	<section class="panel">
		{#if (role==='system_administrator'||role==='business_administrator')}<form onsubmit={(event)=>{event.preventDefault();void save();}}><label>Code<input bind:value={form.code} required maxlength="64" /></label>
			{#if resource==='it-asset-types'||resource==='manufacturers'||resource==='it-asset-statuses'}<label>Name<input bind:value={form.name} required maxlength="128" /></label>{/if}
			{#if resource==='it-asset-types'}<label>Management code prefix<input bind:value={form.managementCodePrefix} required minlength="3" maxlength="5" pattern={'[A-Z]{3,5}'} placeholder="e.g. NPC" /></label>{/if}
			{#if resource==='cpu-types'}<label>Manufacturer<select bind:value={form.manufacturerId} required>{#each manufacturers as maker}<option value={maker.id}>{maker.name}</option>{/each}</select></label><label>Series<input bind:value={form.series} required /></label><label>Model number<input bind:value={form.modelNumber} required /></label><label>Display name<input bind:value={form.displayName} required /></label>{/if}
			{#if resource==='operating-systems'}<label>Vendor<input bind:value={form.vendor} required /></label><label>Product<input bind:value={form.product} required /></label><label>Version<input bind:value={form.version} required /></label><label>Edition<input bind:value={form.edition} /></label><label>Architecture<input bind:value={form.architecture} /></label><label>Display name<input bind:value={form.displayName} required /></label>{/if}
			{#if resource==='manufacturers'||resource==='cpu-types'||resource==='operating-systems'}<label>Official URL<input bind:value={form.officialUrl} type="url" maxlength="1000" /></label><label>Source checked<input bind:value={form.sourceCheckedOn} type="date" /></label>{/if}
			{#if resource==='it-asset-statuses'}<label>Disposal date<select bind:value={form.disposalDatePolicy}><option value="prohibited">Prohibited</option><option value="optional">Optional</option><option value="required">Required</option></select></label>{/if}
			<label>Sort order<input bind:value={form.sortOrder} type="number" min="0" required /></label>
			{#if resource==='it-asset-types'}<fieldset><legend>Supported fields</legend><label><input bind:checked={form.supportsCpu} type="checkbox" />CPU</label><label><input bind:checked={form.supportsRam} type="checkbox" />RAM</label><label><input bind:checked={form.supportsOs} type="checkbox" />OS</label><label><input bind:checked={form.supportsLoginUsername} type="checkbox" />Login username</label></fieldset>{/if}
			<div class="actions"><button class="primary" type="submit">{editing?'Save changes':'Add item'}</button>{#if editing}<button class="secondary" type="button" onclick={reset}>Cancel</button>{/if}</div></form>{/if}
		<div class="table-wrap"><table><thead><tr><th>Code</th><th>Name</th><th>Details</th><th>Order</th>{#if (role==='system_administrator'||role==='business_administrator')}<th></th>{/if}</tr></thead><tbody>{#each items as item}<tr><td><strong>{item.code}</strong></td><td>{item.name??item.displayName}</td><td>{#if resource==='cpu-types'}{item.manufacturer?.name} / {item.series} / {item.modelNumber}{:else if resource==='operating-systems'}{item.vendor} / {item.product} {item.version}{:else if resource==='it-asset-statuses'}Disposal date: {item.disposalDatePolicy}{:else if resource==='it-asset-types'}{item.managementCodePrefix} · {[item.supportsCpu?'CPU':'',item.supportsRam?'RAM':'',item.supportsOs?'OS':'',item.supportsLoginUsername?'Login':''].filter(Boolean).join(', ')||'No optional fields'}{:else}{item.officialUrl??'—'}{/if}</td><td>{item.sortOrder}</td>{#if (role==='system_administrator'||role==='business_administrator')}<td class="row-actions"><button onclick={()=>edit(item)}>Edit</button><button class="danger" onclick={()=>void remove(item)}>Delete</button></td>{/if}</tr>{:else}<tr><td colspan={(role==='system_administrator'||role==='business_administrator')?5:4} class="empty">No items found.</td></tr>{/each}</tbody></table></div>
	</section>
</AssetManagementShell>
<style>.heading{margin-bottom:22px}.heading p{margin:0;color:#1abb9c;font-size:11px;font-weight:700;letter-spacing:.08em}.heading h1{margin:4px 0;font-size:30px}.heading span{color:var(--muted)}.notice{color:#d09b27}.panel{padding:20px;background:var(--surface);border:1px solid var(--border);border-radius:6px}form{display:grid;grid-template-columns:repeat(4,minmax(130px,1fr));gap:10px;margin-bottom:20px;padding:14px;background:var(--surface-secondary);border:1px solid var(--border);border-radius:5px}label{display:grid;gap:5px;font-size:12px}input,select{padding:8px;border:1px solid var(--border);border-radius:4px;background:var(--surface);color:var(--text)}fieldset{display:flex;align-items:center;gap:12px;margin:0;padding:7px 10px;border:1px solid var(--border);border-radius:4px}fieldset legend{font-size:11px}fieldset label{display:flex;align-items:center;gap:4px}.actions{display:flex;align-items:end;gap:8px}.actions button{height:35px;padding:0 12px;border-radius:4px}.primary{background:#066fd1!important;color:#fff!important}.secondary{background:#6c757d!important;color:#fff!important}.table-wrap{overflow:auto}table{width:100%;min-width:720px;border-collapse:collapse}th,td{padding:11px;border-bottom:1px solid var(--border);text-align:left}.row-actions{text-align:right;white-space:nowrap}.row-actions button{background:transparent!important;color:#066fd1!important}.row-actions .danger{color:#d63939!important}.empty{text-align:center;color:var(--muted)}@media(max-width:900px){form{grid-template-columns:1fr 1fr}}@media(max-width:560px){form{grid-template-columns:1fr}}</style>
