<script lang="ts">
	import { onMount } from 'svelte';
	import { apiData } from '$lib/api';
	import AssetManagementShell from '$lib/components/AssetManagementShell.svelte';
	type Item = { id: number; code: string; name: string };
	const resources = [{ key: 'departments', label: 'Departments' }, { key: 'employee-groups', label: 'Groups' }, { key: 'positions', label: 'Positions' }, { key: 'employment-types', label: 'Employment types' }, { key: 'branches', label: 'Branches' }];
	let resource = $state(resources[0].key); let items = $state<Item[]>([]); let code = $state(''); let name = $state(''); let editing = $state<Item | null>(null); let message = $state(''); let canManage = $state(false);
	const endpoint = () => '/v1/' + resource;
	async function load() { const response = await fetch(endpoint()); if (!response.ok) { message = 'Unable to load master data.'; return; } items = await apiData<Item[]>(response); }
	function reset() { editing = null; code = ''; name = ''; }
	async function save() { const response = await fetch(endpoint() + (editing ? '/' + editing.id : ''), { method: editing ? 'PATCH' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ code, name }) }); if (!response.ok) { message = 'Unable to save this item.'; return; } reset(); await load(); }
	async function remove(item: Item) { if (!confirm('Delete ' + item.name + '?')) return; const response = await fetch(endpoint() + '/' + item.id, { method: 'DELETE' }); if (!response.ok) { message = 'This item is in use or could not be deleted.'; return; } await load(); }
	onMount(() => { const selected = new URLSearchParams(window.location.search).get('resource'); if (resources.some((item) => item.key === selected)) resource = selected!; void (async () => { const response = await fetch('/v1/auth/session'); if (response.ok) { const session = await apiData<{ user: { role: string } }>(response); canManage = session.user.role === 'system_administrator' || session.user.role === 'business_administrator'; } await load(); })(); });
</script>
<AssetManagementShell title="Employee masters" active=""><div class="heading"><p>CONFIGURATION</p><div class="title-row"><h1>Employee masters</h1><span>{resources.find((item) => item.key === resource)?.label}</span></div></div><section>{#if canManage}<form onsubmit={(event) => { event.preventDefault(); void save(); }}><input bind:value={code} placeholder="Code" required maxlength="64" /><input bind:value={name} placeholder="Name" required maxlength="128" /><button type="submit">{editing ? 'Save' : 'Add'}</button>{#if editing}<button type="button" onclick={reset}>Cancel</button>{/if}</form>{/if}{#if message}<p role="alert">{message}</p>{/if}<table><thead><tr><th>Code</th><th>Name</th>{#if canManage}<th></th>{/if}</tr></thead><tbody>{#each items as item}<tr><td>{item.code}</td><td>{item.name}</td>{#if canManage}<td class="row-actions"><button class="edit" type="button" onclick={() => { editing = item; code = item.code; name = item.name; }}>Edit</button><button class="danger" type="button" onclick={() => void remove(item)}>Delete</button></td>{/if}</tr>{/each}</tbody></table></section></AssetManagementShell>
<style>.heading{margin-bottom:24px}.heading p{color:#1abb9c;font-size:11px;font-weight:700}.title-row{display:flex;align-items:center;gap:16px}.heading h1{margin:4px 0;font-size:30px}section{padding:20px;background:var(--surface);border:1px solid var(--border);border-radius:6px}form{display:flex;gap:10px;margin-bottom:20px}input{padding:8px;border:1px solid var(--border);border-radius:4px;background:var(--surface);color:var(--text)}button{padding:8px 12px;background:#1abb9c;color:#fff;border:1px solid #169f85;border-radius:4px}table{width:100%;border-collapse:collapse}th,td{padding:12px;border-bottom:1px solid var(--border);text-align:left}.row-actions{text-align:right;white-space:nowrap}.row-actions .edit,.row-actions .danger{display:inline-flex;align-items:center;justify-content:center;height:28px;padding:0 10px;border-radius:4px;font-size:12px;font-weight:500}.row-actions .edit{background:#066fd1!important;border-color:#066fd1;color:#fff}.row-actions .danger{margin-left:6px;background:#d63939!important;border-color:#c92f2f;color:#fff}</style>
