CREATE TABLE public.master_change_history (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key uuid NOT NULL DEFAULT gen_random_uuid(),
    resource text NOT NULL,
    resource_id integer NOT NULL,
    actor_id integer NOT NULL,
    action varchar(20) NOT NULL,
    changes jsonb NOT NULL,
    changed_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamptz(3),
    CONSTRAINT master_change_history_event_key_key UNIQUE (event_key),
    CONSTRAINT master_change_history_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.employees(id) ON DELETE RESTRICT
);

CREATE INDEX master_change_history_resource_resource_id_changed_at_idx ON public.master_change_history(resource, resource_id, changed_at);
CREATE INDEX master_change_history_actor_id_idx ON public.master_change_history(actor_id);

INSERT INTO public.master_change_history (event_key, resource, resource_id, actor_id, action, changes, changed_at, created_at, updated_at)
SELECT event_key, resource, resource_id, actor_id, action, '[]'::jsonb, created_at, created_at, created_at
FROM public.audit_logs
WHERE deleted_at IS NULL
  AND resource IN ('departments', 'employee-groups', 'positions', 'employment-types', 'branches', 'room', 'storage', 'it-asset-types', 'manufacturers', 'cpu-types', 'operating-systems', 'it-asset-statuses', 'role', 'external_link')
  AND action IN ('create', 'update', 'delete', 'restore');
