<script lang="ts">
	import { onMount, tick } from 'svelte';
	import { apiData } from '$lib/api';
	import AssetManagementShell from '$lib/components/AssetManagementShell.svelte';
	import MasterList from '$lib/components/MasterList.svelte';
	import SearchSelect from '$lib/components/SearchSelect.svelte';
	import '$lib/styles/add-button.css';
	type Branch={id:number;code:string;name:string};
	type Room={id:number;code:string;name:string;floor:string|null;branchId:number;branch:Branch};
	type Location={id:number;code:string;name:string;kind:string|null;roomId:number;room:Room};
	type Tab='branches'|'rooms'|'locations';
	let { kind: tab }: { kind: Tab } = $props();
	let role=$state(''); let branches=$state<Branch[]>([]); let rooms=$state<Room[]>([]); let message=$state(''); let editingId=$state<number|null>(null);
	let form=$state({code:'',name:'',branchId:'',floor:'',roomId:'',kind:''});
	let formOpen=$state(false);
	let errors=$state<Record<string,string>>({});let formElement=$state<HTMLFormElement>();
	let list=$state<MasterList>();
	let endpoint=$derived(tab==='locations'?'/v1/storage-locations':`/v1/${tab}`);
	let columns=$derived(tab==='branches'?[{key:'code',label:'Code',value:(item:Branch)=>item.code},{key:'name',label:'Name',value:(item:Branch)=>item.name}]:tab==='rooms'?[{key:'code',label:'Code',value:(item:Room)=>item.code},{key:'name',label:'Name',value:(item:Room)=>item.name},{key:'branch',label:'Branch',value:(item:Room)=>item.branch.name},{key:'floor',label:'Floor',value:(item:Room)=>item.floor??''}]:[{key:'code',label:'Code',value:(item:Location)=>item.code},{key:'name',label:'Name',value:(item:Location)=>item.name},{key:'branch',label:'Branch',value:(item:Location)=>item.room.branch.name},{key:'room',label:'Room',value:(item:Location)=>item.room.name},{key:'kind',label:'Kind',value:(item:Location)=>item.kind??''}]);
	let canManage=$derived(role==='system_administrator'||role==='business_administrator');
	const title=$derived(tab==='branches'?'Branches':tab==='rooms'?'Rooms':'Storages');
	function reset(){editingId=null;formOpen=false;errors={};form={code:'',name:'',branchId:branches[0]?String(branches[0].id):'',floor:'',roomId:rooms[0]?String(rooms[0].id):'',kind:''};message='';}
	async function load(){const session=await fetch('/v1/auth/session');if(!session.ok){message='Please sign in to continue.';return;}role=(await apiData<{user:{role:string}}>(session)).user.role;const responses=await Promise.all([fetch('/v1/branches?limit=500'),fetch('/v1/rooms?limit=500')]);if(responses.some((response)=>!response.ok)){message='Unable to load location data.';return;}[branches,rooms]=await Promise.all([apiData<Branch[]>(responses[0]),apiData<Room[]>(responses[1])]);if(!editingId)reset();}
	function edit(item:Branch|Room|Location){editingId=item.id;formOpen=true;errors={};form={code:item.code,name:item.name,branchId:'branchId' in item?String(item.branchId):'',floor:'floor' in item?item.floor??'':'',roomId:'roomId' in item?String(item.roomId):'',kind:'kind' in item?item.kind??'':''};void tick().then(()=>formElement?.querySelector<HTMLInputElement>('[name="code"]')?.focus());}
	function add(){reset();formOpen=true;void tick().then(()=>formElement?.querySelector<HTMLInputElement>('[name="code"]')?.focus());}
	async function save(){errors={...(!form.code.trim()?{code:'Code is required.'}:{}),...(!form.name.trim()?{name:'Name is required.'}:{}),...(tab==='rooms'&&!form.branchId?{branchId:'Branch is required.'}:{}),...(tab==='locations'&&!form.roomId?{roomId:'Room is required.'}:{})};if(Object.keys(errors).length){await tick();formElement?.querySelector<HTMLElement>('[aria-invalid="true"]')?.focus();return;}const body=tab==='branches'?{code:form.code,name:form.name}:tab==='rooms'?{code:form.code,name:form.name,branchId:form.branchId,floor:form.floor}:{code:form.code,name:form.name,roomId:form.roomId,kind:form.kind};const response=await fetch(`${endpoint}${editingId?'/'+editingId:''}`,{method:editingId?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!response.ok){const payload=await response.json().catch(()=>null) as {error?:{details?:{field?:string}[]}}|null;const field=payload?.error?.details?.[0]?.field;if(field==='code'||field==='name'){errors[field]='This value already exists.';await tick();formElement?.querySelector<HTMLElement>('[aria-invalid="true"]')?.focus();}else message='Unable to save this item. Check required fields and duplicate values.';return;}await load();reset();await list?.refresh();}
	async function remove(item:Branch|Room|Location){if(!confirm(`Delete ${item.name}?`))return;const response=await fetch(`${endpoint}/${item.id}`,{method:'DELETE'});if(!response.ok){message='This item is in use or could not be deleted.';return;}await load();reset();await list?.refresh();}
	onMount(()=>{void load()});
</script>
<AssetManagementShell {title} active="">
	<div class="heading"><div><p>LOCATION HIERARCHY</p><h1>{title}</h1><span>Maintain {tab==='branches'?'branches':tab==='rooms'?'rooms':'storage positions'} used by assets.</span></div>{#if canManage}<button class="app-add-button" type="button" onclick={add}><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M8 2v12M2 8h12" /></svg>Add item</button>{/if}</div>
	{#if message}<p class="notice">{message}</p>{/if}
	<section class="panel">
		{#if canManage && formOpen}<form bind:this={formElement} novalidate onsubmit={(event)=>{event.preventDefault();void save();}}><label>Code <span class="required">*</span><input name="code" bind:value={form.code} maxlength="64" aria-invalid={!!errors.code} aria-describedby={errors.code?'location-code-error':undefined} oninput={()=>errors.code=''}/>{#if errors.code}<small id="location-code-error" class="field-error">{errors.code}</small>{/if}</label><label>Name <span class="required">*</span><input bind:value={form.name} maxlength="128" aria-invalid={!!errors.name} aria-describedby={errors.name?'location-name-error':undefined} oninput={()=>errors.name=''}/>{#if errors.name}<small id="location-name-error" class="field-error">{errors.name}</small>{/if}</label>{#if tab==='rooms'}<SearchSelect label="Branch" field="location-branch" value={form.branchId} options={branches.map((branch)=>({value:String(branch.id),label:branch.name}))} required error={errors.branchId??''} onSelect={(value)=>{form.branchId=value;errors.branchId='';}}/><label>Floor<input bind:value={form.floor} maxlength="64" placeholder="e.g. 3F" /></label>{:else if tab==='locations'}<SearchSelect label="Room" field="location-room" value={form.roomId} options={rooms.map((room)=>({value:String(room.id),label:`${room.branch.name} / ${room.name}`}))} required error={errors.roomId??''} onSelect={(value)=>{form.roomId=value;errors.roomId='';}}/><label>Kind<input bind:value={form.kind} maxlength="64" placeholder="e.g. ROOM" /></label>{/if}<div class="actions"><button class="primary" type="submit">Save</button><button class="secondary" type="button" onclick={reset}>Cancel</button></div></form>{/if}
		<MasterList bind:this={list} {endpoint} {columns} {title} {canManage} onEdit={(item)=>edit(item as Branch|Room|Location)} onDelete={(item)=>remove(item as Branch|Room|Location)} />
	</section>
</AssetManagementShell>
<style>.heading{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:24px}.heading p{margin:0;color:#1abb9c;font-size:11px;font-weight:700}.heading h1{margin:4px 0;font-size:30px}.heading span{color:var(--muted);font-size:13px}.notice{color:#d63939}.panel{width:100%;min-width:0;box-sizing:border-box}form{display:grid;grid-template-columns:repeat(4,minmax(120px,1fr));gap:10px;margin-bottom:20px;padding:14px;background:var(--surface-secondary);border:1px solid var(--border);border-radius:5px}label{display:grid;gap:5px;font-size:12px}input{height:36px;padding:0 12px;border:1px solid var(--border);border-radius:4px;background:var(--surface);color:var(--text)}.actions{display:flex;align-items:end;gap:8px}.actions button{height:35px;padding:0 12px;border:0;border-radius:4px;color:white}.primary{background:#066fd1}.secondary{background:#6c757d}@media(max-width:800px){form{grid-template-columns:1fr 1fr}}@media(max-width:700px){.heading{align-items:stretch;flex-direction:column}}@media(max-width:520px){form{grid-template-columns:1fr}}.required{color:#d63939}input[aria-invalid=true]{border-color:#d63939}.field-error{color:#d63939;font-size:11px}</style>
