<script lang="ts">
	import { tick } from 'svelte';
	type Option={value:string;label:string};
	let {label,field,value,options,onSelect,required=false,error=''}:{label:string;field:string;value:string;options:Option[];onSelect:(value:string)=>void;required?:boolean;error?:string}=$props();
	let open=$state(false);let query=$state('');let above=$state(false);let active=$state(0);let trigger=$state<HTMLButtonElement>();let input=$state<HTMLInputElement>();let root=$state<HTMLDivElement>();
	let filtered=$derived(options.filter((option)=>option.label.toLocaleLowerCase().includes(query.toLocaleLowerCase())));
	function close(focus=false){open=false;query='';if(focus)void tick().then(()=>trigger?.focus());}
	async function show(initial=''){const rect=trigger?.getBoundingClientRect();const spaceBelow=rect?window.innerHeight-rect.bottom:0;above=Boolean(rect&&spaceBelow<210&&rect.top>spaceBelow);query=initial;active=0;open=true;await tick();input?.focus();}
	function choose(option:Option){onSelect(option.value);close(true);}
	function keydown(event:KeyboardEvent){if(event.key==='Escape'){event.preventDefault();close(true);return;}if(event.key==='Tab'){close();return;}if(!open){if(event.key==='Enter'||event.key===' '||event.key==='ArrowDown'){event.preventDefault();void show();return;}if(event.key.length===1&&!event.ctrlKey&&!event.altKey&&!event.metaKey){event.preventDefault();void show(event.key);return;}return;}if(event.key==='ArrowDown'||event.key==='ArrowUp'||event.key==='Home'||event.key==='End'){event.preventDefault();active=event.key==='Home'?0:event.key==='End'?filtered.length-1:event.key==='ArrowDown'?Math.min(active+1,filtered.length-1):Math.max(active-1,0);void tick().then(()=>root?.querySelectorAll<HTMLElement>('[role="option"]')[active]?.scrollIntoView({block:'nearest'}));}else if(event.key==='Enter'&&filtered[active]){event.preventDefault();choose(filtered[active]);}}
	function blur(event:FocusEvent){if(open&&!(event.relatedTarget instanceof Node&&root?.contains(event.relatedTarget)))close();}
</script>
<div bind:this={root} class="select-field" class:above onfocusout={blur}>
	<span id={`${field}-label`}>{label}{#if required} <span class="required" aria-hidden="true">*</span>{/if}</span>
	<button bind:this={trigger} type="button" role="combobox" class="trigger" class:invalid={!!error} aria-labelledby={`${field}-label`} aria-haspopup="listbox" aria-controls={`${field}-options`} aria-expanded={open} aria-required={required} aria-invalid={!!error} aria-describedby={error?`${field}-error`:undefined} onclick={()=>open?close(true):void show()} onkeydown={keydown}><span>{options.find((option)=>option.value===value)?.label??'-'}</span><svg viewBox="0 0 10 6" aria-hidden="true"><path d="M1 1l4 4 4-4"/></svg></button>
	{#if open}<div class="panel"><input bind:this={input} type="search" value={query} aria-label={`Search ${label}`} placeholder="Search..." oninput={(event)=>{query=event.currentTarget.value;active=0;}} onkeydown={keydown}/><div id={`${field}-options`} class="options" role="listbox" aria-label={label}>{#each filtered as option,index}<button type="button" role="option" tabindex="-1" class:active={active===index} class:selected={value===option.value} aria-selected={value===option.value} onclick={()=>choose(option)} onmouseenter={()=>active=index} onkeydown={keydown}>{option.label}</button>{:else}<p>No options found.</p>{/each}</div></div>{/if}
	{#if error}<small id={`${field}-error`} class="error">{error}</small>{/if}
</div>
<style>
	.select-field{position:relative;min-width:0;font-size:12px}.select-field>span{display:block;margin-bottom:5px}.required,.error{color:#d63939}.error{display:block;margin-top:4px;font-size:11px}.trigger{display:flex;align-items:center;justify-content:space-between;gap:8px;width:100%;height:36px;padding:0 12px;background:var(--surface)!important;color:var(--text)!important;border:1px solid var(--border);border-radius:4px;text-align:left;font-size:13px}.trigger>span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.trigger svg{flex:none;width:10px;height:6px;fill:none;stroke:var(--muted);stroke-width:1.5}.trigger[aria-expanded=true] svg{transform:rotate(180deg)}.trigger:hover{border-color:var(--muted)}.trigger:focus-visible,.trigger[aria-expanded=true]{outline:0;border-color:#1abb9c;box-shadow:0 0 0 3px rgba(26,187,156,.14)}.trigger.invalid{border-color:#d63939}.panel{position:absolute;top:calc(100% + 4px);left:0;z-index:30;width:100%;padding:3px;background:var(--surface);border:1px solid var(--border);border-radius:6px;box-shadow:0 8px 18px rgba(0,0,0,.2)}.above .panel{top:auto;bottom:calc(100% + 4px)}.panel input{width:100%;height:30px;padding:0 8px;border:1px solid var(--border);border-radius:4px;background:var(--surface);color:var(--text)}.panel input:focus{outline:2px solid #1abb9c}.options{max-height:200px;overflow:auto}.options button{display:block;width:100%;min-height:28px;padding:5px 7px;background:transparent!important;color:var(--text)!important;border:0;border-radius:3px;text-align:left;font-size:12px}.options button.active{background:var(--surface-secondary)!important}.options button.selected{background:#1abb9c!important;color:#fff!important}.options p{margin:6px;color:var(--muted);font-size:12px}
</style>
